### PR TITLE
Update service location

### PR DESCRIPTION
**Pull request by AlasdairGray**
The OOPS rest service URL has changed. This patch updates the plugin to reflect that change.

I took the liberty to bump the minor software version up to 1.0.2 to reflect the change.

### CODE REVIEW

**Comment by lukasged** [comment]
Hi Alasdair, thanks for the PR!

Did it work for you integrated into Protege? I attach the built plugin package which I tried. The ontology evaluation keeps failing for me. Maybe there were some other changes in the Web Service ?
[oops-1.0.2.jar.zip](https://github.com/lukasged/oops-plugin/files/4689940/oops-1.0.2.jar.zip)

**Comment by AlasdairGray** [comment]
There is some instability with the service itself. It worked for me the other day but it has been intermittent. María Poveda (@mariapoveda) has been interacting with me on it. She's taken a fork of this repo and has asked me to repeat the PR on their [repo](https://github.com/oeg-upm/oops-plugin)

**Comment by mariapoveda** [comment]
It is working for me in Protégé5.5.

@AlasdairGray you can PR in this repo and we can fork again at OEG's one.

**Comment by lukasged** [comment]
Thanks for the comments @AlasdairGray @mariapoveda . 

I tested again and indeed it's working with many ontologies. I was previously trying with some bigger ontologies (e.g. [Ontology of Laboratory Animal Medicine](http://aber-owl.net/media/ontologies/OLAM/5/olam.owl)) and for some reason the plugin fails with them (only the plugin fails; evaluation through the website http://oops.linkeddata.es/ still works for those ontologies).

I will merge this PR.

**Pull request merged**
